// Generated by scripts/generate-content.mjs. Do not edit.
// Summary fields only — full lab content is lazily imported per slug from
// src/content/labs/<slug>.ts. Regenerate with `npm run build`.
import type { LabCategory, Difficulty } from "./types";

export interface LabSummary {
  slug: string;
  title: string;
  category: LabCategory;
  difficulty: Difficulty;
  readingTimeMin: number;
  blurb: string;
}

export const labSummaries: LabSummary[] = [
  {
    "slug": "activity-selection",
    "title": "Activity Selection",
    "category": "Algorithms",
    "difficulty": "Beginner",
    "readingTimeMin": 3,
    "blurb": "Greedily choose compatible activities with equal value."
  },
  {
    "slug": "array",
    "title": "Array",
    "category": "Data Structures",
    "difficulty": "Beginner",
    "readingTimeMin": 3,
    "blurb": "Contiguous memory with constant-time indexed access."
  },
  {
    "slug": "astar-search",
    "title": "A* Search",
    "category": "Algorithms",
    "difficulty": "Intermediate",
    "readingTimeMin": 5,
    "blurb": "Heuristic-based pathfinding."
  },
  {
    "slug": "avl-tree",
    "title": "AVL Tree",
    "category": "Data Structures",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "Self-balancing BST with strict height guarantees."
  },
  {
    "slug": "b-plus-tree",
    "title": "B+ Tree",
    "category": "Data Structures",
    "difficulty": "Advanced",
    "readingTimeMin": 6,
    "blurb": "Disk-friendly ordered index with linked leaf pages."
  },
  {
    "slug": "backpressure",
    "title": "Backpressure",
    "category": "Distributed Systems",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Keep producers from overwhelming consumers with buffers, drops, or throttling."
  },
  {
    "slug": "bellman-ford",
    "title": "Bellman-Ford",
    "category": "Algorithms",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "Shortest paths with negative edges and cycle detection."
  },
  {
    "slug": "binary-search-tree",
    "title": "Binary Search Tree",
    "category": "Data Structures",
    "difficulty": "Beginner",
    "readingTimeMin": 4,
    "blurb": "Ordered tree where left is smaller and right is larger."
  },
  {
    "slug": "binary-search",
    "title": "Binary Search",
    "category": "Algorithms",
    "difficulty": "Beginner",
    "readingTimeMin": 4,
    "blurb": "Find a target in sorted data by halving the search space."
  },
  {
    "slug": "binary-tree",
    "title": "Binary Tree",
    "category": "Data Structures",
    "difficulty": "Beginner",
    "readingTimeMin": 4,
    "blurb": "Hierarchical nodes with at most two children."
  },
  {
    "slug": "bipartite-check",
    "title": "Bipartite Check",
    "category": "Algorithms",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Determine whether a graph can be colored with two sets."
  },
  {
    "slug": "bipartite-matching",
    "title": "Bipartite Matching",
    "category": "Algorithms",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "Pair left and right sets with augmenting paths."
  },
  {
    "slug": "bitset",
    "title": "Bitset",
    "category": "Data Structures",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Pack boolean flags into bits for memory-efficient sets."
  },
  {
    "slug": "bloom-filter",
    "title": "Bloom Filter",
    "category": "Data Structures",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Probabilistic set membership in O(k) bits."
  },
  {
    "slug": "branch-and-bound",
    "title": "Branch and Bound",
    "category": "Algorithms",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "Search optimization branches while pruning hopeless states."
  },
  {
    "slug": "btree-index",
    "title": "B-Tree Index",
    "category": "Data Structures",
    "difficulty": "Advanced",
    "readingTimeMin": 6,
    "blurb": "Insert keys and watch nodes split — Postgres-style."
  },
  {
    "slug": "bucket-sort",
    "title": "Bucket Sort",
    "category": "Algorithms",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Distribute values into buckets, sort locally, then concatenate."
  },
  {
    "slug": "cap-theorem",
    "title": "CAP Theorem",
    "category": "Distributed Systems",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "Pick CP or AP — partition is non-negotiable."
  },
  {
    "slug": "circuit-breaker",
    "title": "Circuit Breaker",
    "category": "Distributed Systems",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Fail fast when a dependency is unhealthy instead of piling on retries."
  },
  {
    "slug": "circular-buffer",
    "title": "Circular Buffer",
    "category": "Data Structures",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Fixed-size ring storage with wrapping head and tail pointers."
  },
  {
    "slug": "coin-change",
    "title": "Coin Change",
    "category": "Algorithms",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Compute minimum coins or number of ways for a target amount."
  },
  {
    "slug": "connected-components",
    "title": "Connected Components",
    "category": "Algorithms",
    "difficulty": "Beginner",
    "readingTimeMin": 4,
    "blurb": "Group reachable nodes in an undirected graph."
  },
  {
    "slug": "consistent-hashing",
    "title": "Consistent Hashing",
    "category": "Distributed Systems",
    "difficulty": "Intermediate",
    "readingTimeMin": 5,
    "blurb": "Add/remove nodes and remap only ~K/N keys."
  },
  {
    "slug": "continuous-batching",
    "title": "Continuous Batching",
    "category": "AI Systems",
    "difficulty": "Intermediate",
    "readingTimeMin": 5,
    "blurb": "A work queue with a scheduler, where the workers are GPU batch slots."
  },
  {
    "slug": "cors-lab",
    "title": "CORS",
    "category": "Security",
    "difficulty": "Beginner",
    "readingTimeMin": 4,
    "blurb": "Origins and Preflights."
  },
  {
    "slug": "counting-sort",
    "title": "Counting Sort",
    "category": "Algorithms",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Linear-time sorting for small integer ranges."
  },
  {
    "slug": "crdt-counter",
    "title": "CRDT G-Counter",
    "category": "Distributed Systems",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "Conflict-free replicated data that converges without coordination."
  },
  {
    "slug": "cycle-detection",
    "title": "Cycle Detection",
    "category": "Algorithms",
    "difficulty": "Intermediate",
    "readingTimeMin": 5,
    "blurb": "Detect loops in directed and undirected graphs."
  },
  {
    "slug": "deadlock",
    "title": "Dining Philosophers — Deadlock",
    "category": "Distributed Systems",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "5 philosophers, 5 forks, one classic deadlock."
  },
  {
    "slug": "deque",
    "title": "Deque",
    "category": "Data Structures",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Double-ended queue for front and back operations."
  },
  {
    "slug": "dijkstra",
    "title": "Dijkstra Pathfinder",
    "category": "Algorithms",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Shortest path on a weighted grid."
  },
  {
    "slug": "disjoint-set-union",
    "title": "Disjoint Set Union",
    "category": "Data Structures",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Track connected components with union-find."
  },
  {
    "slug": "distributed-tx",
    "title": "Saga vs 2PC",
    "category": "Distributed Systems",
    "difficulty": "Advanced",
    "readingTimeMin": 6,
    "blurb": "2-Phase Commit vs Eventual Sagas."
  },
  {
    "slug": "dynamic-array",
    "title": "Dynamic Array",
    "category": "Data Structures",
    "difficulty": "Beginner",
    "readingTimeMin": 4,
    "blurb": "Growable array with amortized O(1) append."
  },
  {
    "slug": "edmonds-karp",
    "title": "Edmonds-Karp",
    "category": "Algorithms",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "Max flow using BFS shortest augmenting paths."
  },
  {
    "slug": "external-merge-sort",
    "title": "External Merge Sort",
    "category": "Algorithms",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "Sort datasets larger than memory with run generation and k-way merge."
  },
  {
    "slug": "fenwick-tree",
    "title": "Fenwick Tree",
    "category": "Data Structures",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "Compact prefix sums with lowbit jumps."
  },
  {
    "slug": "fibonacci-memoization",
    "title": "Fibonacci Memoization",
    "category": "Algorithms",
    "difficulty": "Beginner",
    "readingTimeMin": 3,
    "blurb": "Turn exponential recursion into linear work by caching subproblems."
  },
  {
    "slug": "floyd-warshall",
    "title": "Floyd-Warshall",
    "category": "Algorithms",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "All-pairs shortest paths with dynamic programming."
  },
  {
    "slug": "gossip-protocol",
    "title": "Gossip Protocol",
    "category": "Distributed Systems",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "Epidemic state dissemination."
  },
  {
    "slug": "graph-representations",
    "title": "Graph Representations",
    "category": "Algorithms",
    "difficulty": "Beginner",
    "readingTimeMin": 4,
    "blurb": "Adjacency lists vs matrices for storing relationships."
  },
  {
    "slug": "graph-traversal",
    "title": "BFS vs DFS",
    "category": "Algorithms",
    "difficulty": "Beginner",
    "readingTimeMin": 4,
    "blurb": "Same graph, two strategies — Queue vs Stack."
  },
  {
    "slug": "graph-union-find",
    "title": "Graph Union-Find",
    "category": "Algorithms",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Answer dynamic connectivity in undirected graphs."
  },
  {
    "slug": "grid-dp",
    "title": "Grid DP",
    "category": "Algorithms",
    "difficulty": "Beginner",
    "readingTimeMin": 4,
    "blurb": "Solve path/counting problems by combining neighboring cells."
  },
  {
    "slug": "hash-table",
    "title": "Hash Table",
    "category": "Data Structures",
    "difficulty": "Intermediate",
    "readingTimeMin": 5,
    "blurb": "Map keys to buckets for average O(1) lookup."
  },
  {
    "slug": "heap-priority-queue",
    "title": "Heap / Priority Queue",
    "category": "Data Structures",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Tree-backed structure for repeatedly extracting min or max."
  },
  {
    "slug": "heap-sort",
    "title": "Heap Sort",
    "category": "Algorithms",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Sort in-place using a binary heap."
  },
  {
    "slug": "huffman-coding",
    "title": "Huffman Coding",
    "category": "Algorithms",
    "difficulty": "Intermediate",
    "readingTimeMin": 5,
    "blurb": "Build optimal prefix codes from character frequencies."
  },
  {
    "slug": "hyperloglog",
    "title": "HyperLogLog",
    "category": "Data Structures",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "Probabilistic cardinality estimation."
  },
  {
    "slug": "inference-cost",
    "title": "Inference Cost & Latency Budgets",
    "category": "AI Systems",
    "difficulty": "Intermediate",
    "readingTimeMin": 5,
    "blurb": "A token bucket where the tokens cost money and the refill is a GPU."
  },
  {
    "slug": "interval-scheduling",
    "title": "Interval Scheduling",
    "category": "Algorithms",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Select the maximum number of non-overlapping intervals."
  },
  {
    "slug": "jwt-anatomy",
    "title": "JWT Anatomy",
    "category": "Security",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Stateless auth and tampered tokens."
  },
  {
    "slug": "knapsack",
    "title": "0/1 Knapsack",
    "category": "Algorithms",
    "difficulty": "Intermediate",
    "readingTimeMin": 5,
    "blurb": "Choose items under capacity to maximize value."
  },
  {
    "slug": "kruskal-mst",
    "title": "Kruskal MST",
    "category": "Algorithms",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Build an MST by sorting edges and skipping cycles."
  },
  {
    "slug": "kv-cache",
    "title": "KV Cache",
    "category": "AI Systems",
    "difficulty": "Intermediate",
    "readingTimeMin": 5,
    "blurb": "The LRU cache that decides which conversations stay on the GPU."
  },
  {
    "slug": "levenshtein",
    "title": "Levenshtein Distance",
    "category": "Algorithms",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Calculating the cost of change."
  },
  {
    "slug": "linked-list",
    "title": "Linked List",
    "category": "Data Structures",
    "difficulty": "Beginner",
    "readingTimeMin": 4,
    "blurb": "Pointer-linked nodes optimized for local insertion and deletion."
  },
  {
    "slug": "load-balancer",
    "title": "Load Balancing",
    "category": "Distributed Systems",
    "difficulty": "Intermediate",
    "readingTimeMin": 5,
    "blurb": "Route requests with round-robin, least-connections, and weighted strategies."
  },
  {
    "slug": "longest-common-subsequence",
    "title": "Longest Common Subsequence",
    "category": "Algorithms",
    "difficulty": "Intermediate",
    "readingTimeMin": 5,
    "blurb": "Find shared order between two sequences."
  },
  {
    "slug": "longest-increasing-subsequence",
    "title": "Longest Increasing Subsequence",
    "category": "Algorithms",
    "difficulty": "Intermediate",
    "readingTimeMin": 5,
    "blurb": "Find the longest ordered subsequence without requiring contiguity."
  },
  {
    "slug": "lru-cache",
    "title": "LRU Cache",
    "category": "Data Structures",
    "difficulty": "Beginner",
    "readingTimeMin": 3,
    "blurb": "Doubly-linked list + hash map = O(1) eviction."
  },
  {
    "slug": "lsm-tree",
    "title": "LSM Tree",
    "category": "Data Structures",
    "difficulty": "Advanced",
    "readingTimeMin": 6,
    "blurb": "Write-optimized storage engine."
  },
  {
    "slug": "matrix-chain-multiplication",
    "title": "Matrix Chain Multiplication",
    "category": "Algorithms",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "Choose multiplication order that minimizes scalar operations."
  },
  {
    "slug": "max-flow",
    "title": "Max Flow",
    "category": "Algorithms",
    "difficulty": "Advanced",
    "readingTimeMin": 6,
    "blurb": "Push as much flow as possible from source to sink."
  },
  {
    "slug": "merge-sort-recursion",
    "title": "Merge Sort Recursion",
    "category": "Algorithms",
    "difficulty": "Beginner",
    "readingTimeMin": 4,
    "blurb": "Divide arrays into halves, then merge sorted halves."
  },
  {
    "slug": "merkle-tree",
    "title": "Merkle Tree",
    "category": "Data Structures",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Data integrity via cryptographic hashes."
  },
  {
    "slug": "message-queue",
    "title": "Distributed Message Queue",
    "category": "Distributed Systems",
    "difficulty": "Intermediate",
    "readingTimeMin": 5,
    "blurb": "Kafka-style Pub/Sub with partitions and consumer lag."
  },
  {
    "slug": "min-cut",
    "title": "Min Cut",
    "category": "Algorithms",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "Find the smallest capacity separating source from sink."
  },
  {
    "slug": "n-queens",
    "title": "N-Queens",
    "category": "Algorithms",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Backtrack through board placements with constraint pruning."
  },
  {
    "slug": "oidc-flow",
    "title": "OAuth 2.0 / OIDC Flow",
    "category": "Security",
    "difficulty": "Advanced",
    "readingTimeMin": 6,
    "blurb": "Authz-code + PKCE, replay attack, tampered verifier — step by step."
  },
  {
    "slug": "pagerank",
    "title": "PageRank",
    "category": "Algorithms",
    "difficulty": "Advanced",
    "readingTimeMin": 6,
    "blurb": "The logic of influence."
  },
  {
    "slug": "permutations-subsets",
    "title": "Permutations & Subsets",
    "category": "Algorithms",
    "difficulty": "Beginner",
    "readingTimeMin": 4,
    "blurb": "Generate combinatorial search spaces with recursion."
  },
  {
    "slug": "prim-mst",
    "title": "Prim MST",
    "category": "Algorithms",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Grow a minimum spanning tree from one connected frontier."
  },
  {
    "slug": "quadtree",
    "title": "QuadTree / GeoSpatial",
    "category": "Data Structures",
    "difficulty": "Intermediate",
    "readingTimeMin": 5,
    "blurb": "2D spatial partitioning."
  },
  {
    "slug": "quantization",
    "title": "Quantization",
    "category": "AI Systems",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "Packing weights into fewer bits, the way a bitset packs flags."
  },
  {
    "slug": "queue",
    "title": "Queue",
    "category": "Data Structures",
    "difficulty": "Beginner",
    "readingTimeMin": 3,
    "blurb": "First-in, first-out ordering for fair processing."
  },
  {
    "slug": "quickselect",
    "title": "Quickselect",
    "category": "Algorithms",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Find the kth smallest element without fully sorting."
  },
  {
    "slug": "rabin-karp",
    "title": "Rabin-Karp",
    "category": "Algorithms",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Rolling hash string search."
  },
  {
    "slug": "radix-sort",
    "title": "Radix Sort",
    "category": "Algorithms",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "Sort integers or strings digit by digit."
  },
  {
    "slug": "raft-election",
    "title": "Raft Leader Election",
    "category": "Distributed Systems",
    "difficulty": "Advanced",
    "readingTimeMin": 6,
    "blurb": "5-node consensus with crash recovery."
  },
  {
    "slug": "rate-limiter",
    "title": "Rate Limiter Showdown",
    "category": "Distributed Systems",
    "difficulty": "Intermediate",
    "readingTimeMin": 5,
    "blurb": "Token Bucket vs Leaky Bucket vs Fixed Window vs Sliding Log."
  },
  {
    "slug": "red-black-tree",
    "title": "Red-Black Tree",
    "category": "Data Structures",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "Balanced BST using color rules and rotations."
  },
  {
    "slug": "segment-tree",
    "title": "Segment Tree",
    "category": "Data Structures",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "Range queries and point updates in logarithmic time."
  },
  {
    "slug": "sharding-replication",
    "title": "Sharding & Replication",
    "category": "Distributed Systems",
    "difficulty": "Advanced",
    "readingTimeMin": 6,
    "blurb": "Route keys to shards and compare quorum vs asynchronous replication."
  },
  {
    "slug": "skip-list",
    "title": "Skip List",
    "category": "Data Structures",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Probabilistic search structure."
  },
  {
    "slug": "snowflake-id",
    "title": "Snowflake IDs",
    "category": "Distributed Systems",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "K-ordered unique IDs at scale."
  },
  {
    "slug": "sorting-race",
    "title": "Sorting Race",
    "category": "Algorithms",
    "difficulty": "Beginner",
    "readingTimeMin": 3,
    "blurb": "Bubble vs Quick vs Merge — same array, side by side."
  },
  {
    "slug": "sparse-matrix",
    "title": "Sparse Matrix",
    "category": "Data Structures",
    "difficulty": "Intermediate",
    "readingTimeMin": 5,
    "blurb": "Store only non-zero cells instead of the full grid."
  },
  {
    "slug": "speculative-decoding",
    "title": "Speculative Decoding",
    "category": "AI Systems",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "Guess ahead cheaply, verify in bulk, keep the prefix that survives."
  },
  {
    "slug": "stack",
    "title": "Stack",
    "category": "Data Structures",
    "difficulty": "Beginner",
    "readingTimeMin": 3,
    "blurb": "Last-in, first-out storage for nested work."
  },
  {
    "slug": "strongly-connected-components",
    "title": "Strongly Connected Components",
    "category": "Algorithms",
    "difficulty": "Advanced",
    "readingTimeMin": 6,
    "blurb": "Find maximal mutually reachable groups in directed graphs."
  },
  {
    "slug": "timsort",
    "title": "TimSort",
    "category": "Algorithms",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "Production hybrid sort optimized for real-world partially ordered data."
  },
  {
    "slug": "tls-handshake",
    "title": "TLS Handshake",
    "category": "Security",
    "difficulty": "Advanced",
    "readingTimeMin": 6,
    "blurb": "The foundation of HTTPS."
  },
  {
    "slug": "topological-sort",
    "title": "Topological Sort",
    "category": "Algorithms",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Order dependent work in a DAG with Kahn's algorithm."
  },
  {
    "slug": "tree-dp",
    "title": "Tree DP",
    "category": "Algorithms",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "Return multiple states per node and combine child answers."
  },
  {
    "slug": "trie",
    "title": "Trie (Prefix Tree)",
    "category": "Data Structures",
    "difficulty": "Beginner",
    "readingTimeMin": 3,
    "blurb": "The engine of autocomplete."
  },
  {
    "slug": "vector-clocks",
    "title": "Vector Clocks",
    "category": "Distributed Systems",
    "difficulty": "Advanced",
    "readingTimeMin": 6,
    "blurb": "Detecting causality and conflicts."
  },
  {
    "slug": "webauthn",
    "title": "WebAuthn / Passkeys",
    "category": "Security",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "The end of the password."
  }
];

/** Every declared bridge, flattened. Source of truth for both directions. */
export interface BridgeEdge {
  /** The lab that declares the bridge — the newer idea. */
  to: string;
  /** The prerequisite it is a small delta from. */
  from: string;
  sameness: string;
  delta: string;
}

export const bridgeEdges: BridgeEdge[] = [
  {
    "to": "continuous-batching",
    "from": "message-queue",
    "sameness": "It IS a work queue with a fixed pool of workers. Requests arrive, wait for a slot, occupy it for a while, and free it. The batch slots are the consumers and the scheduler decides who gets one next.",
    "delta": "A slot is not held for one message but for hundreds of sequential decode steps, and every occupied slot advances by one token in lockstep each step. So the unit of work is a step across the whole batch, not a message."
  },
  {
    "to": "continuous-batching",
    "from": "backpressure",
    "sameness": "The admission decision is the same one you implemented: a bounded pool, an arrival rate that may exceed it, and a policy for what happens to the excess.",
    "delta": "Rejecting is rarely acceptable here, so the excess queues and the pressure surfaces as time-to-first-token instead of dropped work. KV cache memory, not slot count, is usually the real bound."
  },
  {
    "to": "inference-cost",
    "from": "rate-limiter",
    "sameness": "It is the token bucket you implemented, with the units changed. A budget refills over time, each request draws from it, and exceeding the rate means queueing or rejection.",
    "delta": "The tokens are literally the model's tokens, priced differently for input and output, so the bucket is denominated in money as well as in requests per second."
  },
  {
    "to": "inference-cost",
    "from": "load-balancer",
    "sameness": "Capacity planning is the same arithmetic: concurrency divided by service time gives throughput, and offered load above that queues.",
    "delta": "Service time is not roughly constant. It scales with the number of output tokens, so two requests to the same endpoint can differ by a factor of fifty and capacity is a moving target."
  },
  {
    "to": "kv-cache",
    "from": "lru-cache",
    "sameness": "It IS an LRU cache. Keys are sequences, values are their attention tensors, and the eviction policy is the same recency ordering you implemented — the least recently touched conversation is the one that goes.",
    "delta": "The budget is GPU memory rather than entry count, so entries have wildly different sizes. And an eviction is not a miss you refetch — it is a recompute of every token in that sequence, which is why it shows up as a latency spike rather than an error."
  },
  {
    "to": "quantization",
    "from": "bitset",
    "sameness": "It is the same packing you implemented: values that do not need a full machine word share one, and reading a value means an offset plus a mask. Memory falls geometrically with the bits per value.",
    "delta": "The packed values are approximations rather than exact booleans, so packing now costs accuracy. You also need a scale factor per group to map the small integer range back onto real weights."
  },
  {
    "to": "quantization",
    "from": "huffman-coding",
    "sameness": "Both spend bits in proportion to how much they matter. Huffman gives frequent symbols shorter codes; quantisation gives each weight group only as many levels as its range justifies.",
    "delta": "Quantisation is lossy and fixed-width, so it is chosen for predictable memory and fast decode rather than for optimal compression."
  },
  {
    "to": "speculative-decoding",
    "from": "branch-and-bound",
    "sameness": "It is the same speculate-then-prune shape you implemented: explore a candidate path cheaply, evaluate it against something authoritative, and discard everything after the point it stops holding up.",
    "delta": "The cheap explorer is a small language model rather than a bound function, and verification is exact rather than a heuristic — a rejected token costs wasted GPU time but never a wrong answer."
  }
];
