// Generated by scripts/generate-content.mjs. Do not edit.
// Summary fields only — full lab content is lazily imported per slug from
// src/content/labs/<slug>.ts. Regenerate with `npm run build`.
import type { LabCategory, Difficulty } from "./types";

export interface LabSummary {
  slug: string;
  title: string;
  category: LabCategory;
  difficulty: Difficulty;
  readingTimeMin: number;
  blurb: string;
}

export const labSummaries: LabSummary[] = [
  {
    "slug": "activity-selection",
    "title": "Activity Selection",
    "category": "Algorithms",
    "difficulty": "Beginner",
    "readingTimeMin": 3,
    "blurb": "Greedily choose compatible activities with equal value."
  },
  {
    "slug": "agent-loop",
    "title": "Agent Loop & Tool Use",
    "category": "AI Systems",
    "difficulty": "Advanced",
    "readingTimeMin": 7,
    "blurb": "A dependency graph executed in order — discovered one node at a time."
  },
  {
    "slug": "ann-search",
    "title": "ANN Search & HNSW",
    "category": "AI Systems",
    "difficulty": "Advanced",
    "readingTimeMin": 7,
    "blurb": "A skip list whose ordering is distance — so greedy descent can get it wrong."
  },
  {
    "slug": "array",
    "title": "Array",
    "category": "Data Structures",
    "difficulty": "Beginner",
    "readingTimeMin": 3,
    "blurb": "Contiguous memory with constant-time indexed access."
  },
  {
    "slug": "astar-search",
    "title": "A* Search",
    "category": "Algorithms",
    "difficulty": "Intermediate",
    "readingTimeMin": 5,
    "blurb": "Heuristic-based pathfinding."
  },
  {
    "slug": "attention",
    "title": "Attention as a Lookup Table",
    "category": "AI Systems",
    "difficulty": "Advanced",
    "readingTimeMin": 7,
    "blurb": "Query, key, value — a hash table where every key matches a little."
  },
  {
    "slug": "avl-tree",
    "title": "AVL Tree",
    "category": "Data Structures",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "Self-balancing BST with strict height guarantees."
  },
  {
    "slug": "b-plus-tree",
    "title": "B+ Tree",
    "category": "Data Structures",
    "difficulty": "Advanced",
    "readingTimeMin": 6,
    "blurb": "Disk-friendly ordered index with linked leaf pages."
  },
  {
    "slug": "backpressure",
    "title": "Backpressure",
    "category": "Distributed Systems",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Keep producers from overwhelming consumers with buffers, drops, or throttling."
  },
  {
    "slug": "bellman-ford",
    "title": "Bellman-Ford",
    "category": "Algorithms",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "Shortest paths with negative edges and cycle detection."
  },
  {
    "slug": "binary-search-tree",
    "title": "Binary Search Tree",
    "category": "Data Structures",
    "difficulty": "Beginner",
    "readingTimeMin": 4,
    "blurb": "Ordered tree where left is smaller and right is larger."
  },
  {
    "slug": "binary-search",
    "title": "Binary Search",
    "category": "Algorithms",
    "difficulty": "Beginner",
    "readingTimeMin": 4,
    "blurb": "Find a target in sorted data by halving the search space."
  },
  {
    "slug": "binary-tree",
    "title": "Binary Tree",
    "category": "Data Structures",
    "difficulty": "Beginner",
    "readingTimeMin": 4,
    "blurb": "Hierarchical nodes with at most two children."
  },
  {
    "slug": "bipartite-check",
    "title": "Bipartite Check",
    "category": "Algorithms",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Determine whether a graph can be colored with two sets."
  },
  {
    "slug": "bipartite-matching",
    "title": "Bipartite Matching",
    "category": "Algorithms",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "Pair left and right sets with augmenting paths."
  },
  {
    "slug": "bitset",
    "title": "Bitset",
    "category": "Data Structures",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Pack boolean flags into bits for memory-efficient sets."
  },
  {
    "slug": "bloom-filter",
    "title": "Bloom Filter",
    "category": "Data Structures",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Probabilistic set membership in O(k) bits."
  },
  {
    "slug": "branch-and-bound",
    "title": "Branch and Bound",
    "category": "Algorithms",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "Search optimization branches while pruning hopeless states."
  },
  {
    "slug": "btree-index",
    "title": "B-Tree Index",
    "category": "Data Structures",
    "difficulty": "Advanced",
    "readingTimeMin": 6,
    "blurb": "Insert keys and watch nodes split — Postgres-style."
  },
  {
    "slug": "bucket-sort",
    "title": "Bucket Sort",
    "category": "Algorithms",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Distribute values into buckets, sort locally, then concatenate."
  },
  {
    "slug": "cap-theorem",
    "title": "CAP Theorem",
    "category": "Distributed Systems",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "Pick CP or AP — partition is non-negotiable."
  },
  {
    "slug": "circuit-breaker",
    "title": "Circuit Breaker",
    "category": "Distributed Systems",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Fail fast when a dependency is unhealthy instead of piling on retries."
  },
  {
    "slug": "circular-buffer",
    "title": "Circular Buffer",
    "category": "Data Structures",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Fixed-size ring storage with wrapping head and tail pointers."
  },
  {
    "slug": "coin-change",
    "title": "Coin Change",
    "category": "Algorithms",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Compute minimum coins or number of ways for a target amount."
  },
  {
    "slug": "connected-components",
    "title": "Connected Components",
    "category": "Algorithms",
    "difficulty": "Beginner",
    "readingTimeMin": 4,
    "blurb": "Group reachable nodes in an undirected graph."
  },
  {
    "slug": "consistent-hashing",
    "title": "Consistent Hashing",
    "category": "Distributed Systems",
    "difficulty": "Intermediate",
    "readingTimeMin": 5,
    "blurb": "Add/remove nodes and remap only ~K/N keys."
  },
  {
    "slug": "continuous-batching",
    "title": "Continuous Batching",
    "category": "AI Systems",
    "difficulty": "Intermediate",
    "readingTimeMin": 5,
    "blurb": "A work queue with a scheduler, where the workers are GPU batch slots."
  },
  {
    "slug": "cors-lab",
    "title": "CORS",
    "category": "Security",
    "difficulty": "Beginner",
    "readingTimeMin": 4,
    "blurb": "Origins and Preflights."
  },
  {
    "slug": "counting-sort",
    "title": "Counting Sort",
    "category": "Algorithms",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Linear-time sorting for small integer ranges."
  },
  {
    "slug": "crdt-counter",
    "title": "CRDT G-Counter",
    "category": "Distributed Systems",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "Conflict-free replicated data that converges without coordination."
  },
  {
    "slug": "cycle-detection",
    "title": "Cycle Detection",
    "category": "Algorithms",
    "difficulty": "Intermediate",
    "readingTimeMin": 5,
    "blurb": "Detect loops in directed and undirected graphs."
  },
  {
    "slug": "deadlock",
    "title": "Dining Philosophers — Deadlock",
    "category": "Distributed Systems",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "5 philosophers, 5 forks, one classic deadlock."
  },
  {
    "slug": "deque",
    "title": "Deque",
    "category": "Data Structures",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Double-ended queue for front and back operations."
  },
  {
    "slug": "dijkstra",
    "title": "Dijkstra Pathfinder",
    "category": "Algorithms",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Shortest path on a weighted grid."
  },
  {
    "slug": "disjoint-set-union",
    "title": "Disjoint Set Union",
    "category": "Data Structures",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Track connected components with union-find."
  },
  {
    "slug": "distributed-tx",
    "title": "Saga vs 2PC",
    "category": "Distributed Systems",
    "difficulty": "Advanced",
    "readingTimeMin": 6,
    "blurb": "2-Phase Commit vs Eventual Sagas."
  },
  {
    "slug": "dynamic-array",
    "title": "Dynamic Array",
    "category": "Data Structures",
    "difficulty": "Beginner",
    "readingTimeMin": 4,
    "blurb": "Growable array with amortized O(1) append."
  },
  {
    "slug": "edmonds-karp",
    "title": "Edmonds-Karp",
    "category": "Algorithms",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "Max flow using BFS shortest augmenting paths."
  },
  {
    "slug": "embeddings",
    "title": "Embeddings & Vector Space",
    "category": "AI Systems",
    "difficulty": "Intermediate",
    "readingTimeMin": 6,
    "blurb": "The sparse row you already know, squashed until direction means meaning."
  },
  {
    "slug": "external-merge-sort",
    "title": "External Merge Sort",
    "category": "Algorithms",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "Sort datasets larger than memory with run generation and k-way merge."
  },
  {
    "slug": "fenwick-tree",
    "title": "Fenwick Tree",
    "category": "Data Structures",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "Compact prefix sums with lowbit jumps."
  },
  {
    "slug": "fibonacci-memoization",
    "title": "Fibonacci Memoization",
    "category": "Algorithms",
    "difficulty": "Beginner",
    "readingTimeMin": 3,
    "blurb": "Turn exponential recursion into linear work by caching subproblems."
  },
  {
    "slug": "floyd-warshall",
    "title": "Floyd-Warshall",
    "category": "Algorithms",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "All-pairs shortest paths with dynamic programming."
  },
  {
    "slug": "gossip-protocol",
    "title": "Gossip Protocol",
    "category": "Distributed Systems",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "Epidemic state dissemination."
  },
  {
    "slug": "graph-representations",
    "title": "Graph Representations",
    "category": "Algorithms",
    "difficulty": "Beginner",
    "readingTimeMin": 4,
    "blurb": "Adjacency lists vs matrices for storing relationships."
  },
  {
    "slug": "graph-traversal",
    "title": "BFS vs DFS",
    "category": "Algorithms",
    "difficulty": "Beginner",
    "readingTimeMin": 4,
    "blurb": "Same graph, two strategies — Queue vs Stack."
  },
  {
    "slug": "graph-union-find",
    "title": "Graph Union-Find",
    "category": "Algorithms",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Answer dynamic connectivity in undirected graphs."
  },
  {
    "slug": "grid-dp",
    "title": "Grid DP",
    "category": "Algorithms",
    "difficulty": "Beginner",
    "readingTimeMin": 4,
    "blurb": "Solve path/counting problems by combining neighboring cells."
  },
  {
    "slug": "hash-table",
    "title": "Hash Table",
    "category": "Data Structures",
    "difficulty": "Intermediate",
    "readingTimeMin": 5,
    "blurb": "Map keys to buckets for average O(1) lookup."
  },
  {
    "slug": "heap-priority-queue",
    "title": "Heap / Priority Queue",
    "category": "Data Structures",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Tree-backed structure for repeatedly extracting min or max."
  },
  {
    "slug": "heap-sort",
    "title": "Heap Sort",
    "category": "Algorithms",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Sort in-place using a binary heap."
  },
  {
    "slug": "huffman-coding",
    "title": "Huffman Coding",
    "category": "Algorithms",
    "difficulty": "Intermediate",
    "readingTimeMin": 5,
    "blurb": "Build optimal prefix codes from character frequencies."
  },
  {
    "slug": "hyperloglog",
    "title": "HyperLogLog",
    "category": "Data Structures",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "Probabilistic cardinality estimation."
  },
  {
    "slug": "inference-cost",
    "title": "Inference Cost & Latency Budgets",
    "category": "AI Systems",
    "difficulty": "Intermediate",
    "readingTimeMin": 5,
    "blurb": "A token bucket where the tokens cost money and the refill is a GPU."
  },
  {
    "slug": "interval-scheduling",
    "title": "Interval Scheduling",
    "category": "Algorithms",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Select the maximum number of non-overlapping intervals."
  },
  {
    "slug": "jwt-anatomy",
    "title": "JWT Anatomy",
    "category": "Security",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Stateless auth and tampered tokens."
  },
  {
    "slug": "knapsack",
    "title": "0/1 Knapsack",
    "category": "Algorithms",
    "difficulty": "Intermediate",
    "readingTimeMin": 5,
    "blurb": "Choose items under capacity to maximize value."
  },
  {
    "slug": "kruskal-mst",
    "title": "Kruskal MST",
    "category": "Algorithms",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Build an MST by sorting edges and skipping cycles."
  },
  {
    "slug": "kv-cache",
    "title": "KV Cache",
    "category": "AI Systems",
    "difficulty": "Intermediate",
    "readingTimeMin": 5,
    "blurb": "The LRU cache that decides which conversations stay on the GPU."
  },
  {
    "slug": "levenshtein",
    "title": "Levenshtein Distance",
    "category": "Algorithms",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Calculating the cost of change."
  },
  {
    "slug": "linked-list",
    "title": "Linked List",
    "category": "Data Structures",
    "difficulty": "Beginner",
    "readingTimeMin": 4,
    "blurb": "Pointer-linked nodes optimized for local insertion and deletion."
  },
  {
    "slug": "load-balancer",
    "title": "Load Balancing",
    "category": "Distributed Systems",
    "difficulty": "Intermediate",
    "readingTimeMin": 5,
    "blurb": "Route requests with round-robin, least-connections, and weighted strategies."
  },
  {
    "slug": "longest-common-subsequence",
    "title": "Longest Common Subsequence",
    "category": "Algorithms",
    "difficulty": "Intermediate",
    "readingTimeMin": 5,
    "blurb": "Find shared order between two sequences."
  },
  {
    "slug": "longest-increasing-subsequence",
    "title": "Longest Increasing Subsequence",
    "category": "Algorithms",
    "difficulty": "Intermediate",
    "readingTimeMin": 5,
    "blurb": "Find the longest ordered subsequence without requiring contiguity."
  },
  {
    "slug": "lru-cache",
    "title": "LRU Cache",
    "category": "Data Structures",
    "difficulty": "Beginner",
    "readingTimeMin": 3,
    "blurb": "Doubly-linked list + hash map = O(1) eviction."
  },
  {
    "slug": "lsm-tree",
    "title": "LSM Tree",
    "category": "Data Structures",
    "difficulty": "Advanced",
    "readingTimeMin": 6,
    "blurb": "Write-optimized storage engine."
  },
  {
    "slug": "matrix-chain-multiplication",
    "title": "Matrix Chain Multiplication",
    "category": "Algorithms",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "Choose multiplication order that minimizes scalar operations."
  },
  {
    "slug": "max-flow",
    "title": "Max Flow",
    "category": "Algorithms",
    "difficulty": "Advanced",
    "readingTimeMin": 6,
    "blurb": "Push as much flow as possible from source to sink."
  },
  {
    "slug": "merge-sort-recursion",
    "title": "Merge Sort Recursion",
    "category": "Algorithms",
    "difficulty": "Beginner",
    "readingTimeMin": 4,
    "blurb": "Divide arrays into halves, then merge sorted halves."
  },
  {
    "slug": "merkle-tree",
    "title": "Merkle Tree",
    "category": "Data Structures",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Data integrity via cryptographic hashes."
  },
  {
    "slug": "message-queue",
    "title": "Distributed Message Queue",
    "category": "Distributed Systems",
    "difficulty": "Intermediate",
    "readingTimeMin": 5,
    "blurb": "Kafka-style Pub/Sub with partitions and consumer lag."
  },
  {
    "slug": "min-cut",
    "title": "Min Cut",
    "category": "Algorithms",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "Find the smallest capacity separating source from sink."
  },
  {
    "slug": "n-queens",
    "title": "N-Queens",
    "category": "Algorithms",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Backtrack through board placements with constraint pruning."
  },
  {
    "slug": "oidc-flow",
    "title": "OAuth 2.0 / OIDC Flow",
    "category": "Security",
    "difficulty": "Advanced",
    "readingTimeMin": 6,
    "blurb": "Authz-code + PKCE, replay attack, tampered verifier — step by step."
  },
  {
    "slug": "pagerank",
    "title": "PageRank",
    "category": "Algorithms",
    "difficulty": "Advanced",
    "readingTimeMin": 6,
    "blurb": "The logic of influence."
  },
  {
    "slug": "permutations-subsets",
    "title": "Permutations & Subsets",
    "category": "Algorithms",
    "difficulty": "Beginner",
    "readingTimeMin": 4,
    "blurb": "Generate combinatorial search spaces with recursion."
  },
  {
    "slug": "prim-mst",
    "title": "Prim MST",
    "category": "Algorithms",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Grow a minimum spanning tree from one connected frontier."
  },
  {
    "slug": "prompt-injection",
    "title": "Prompt Injection & Trust Boundaries",
    "category": "AI Systems",
    "difficulty": "Advanced",
    "readingTimeMin": 7,
    "blurb": "Untrusted input arriving as instructions — with no signature to check."
  },
  {
    "slug": "quadtree",
    "title": "QuadTree / GeoSpatial",
    "category": "Data Structures",
    "difficulty": "Intermediate",
    "readingTimeMin": 5,
    "blurb": "2D spatial partitioning."
  },
  {
    "slug": "quantization",
    "title": "Quantization",
    "category": "AI Systems",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "Packing weights into fewer bits, the way a bitset packs flags."
  },
  {
    "slug": "queue",
    "title": "Queue",
    "category": "Data Structures",
    "difficulty": "Beginner",
    "readingTimeMin": 3,
    "blurb": "First-in, first-out ordering for fair processing."
  },
  {
    "slug": "quickselect",
    "title": "Quickselect",
    "category": "Algorithms",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Find the kth smallest element without fully sorting."
  },
  {
    "slug": "rabin-karp",
    "title": "Rabin-Karp",
    "category": "Algorithms",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Rolling hash string search."
  },
  {
    "slug": "radix-sort",
    "title": "Radix Sort",
    "category": "Algorithms",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "Sort integers or strings digit by digit."
  },
  {
    "slug": "raft-election",
    "title": "Raft Leader Election",
    "category": "Distributed Systems",
    "difficulty": "Advanced",
    "readingTimeMin": 6,
    "blurb": "5-node consensus with crash recovery."
  },
  {
    "slug": "rag-pipeline",
    "title": "RAG Retrieval Pipeline",
    "category": "AI Systems",
    "difficulty": "Advanced",
    "readingTimeMin": 7,
    "blurb": "Three labs you already finished, in a row — where the recalls multiply."
  },
  {
    "slug": "rate-limiter",
    "title": "Rate Limiter Showdown",
    "category": "Distributed Systems",
    "difficulty": "Intermediate",
    "readingTimeMin": 5,
    "blurb": "Token Bucket vs Leaky Bucket vs Fixed Window vs Sliding Log."
  },
  {
    "slug": "red-black-tree",
    "title": "Red-Black Tree",
    "category": "Data Structures",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "Balanced BST using color rules and rotations."
  },
  {
    "slug": "reranking",
    "title": "Reranking",
    "category": "AI Systems",
    "difficulty": "Intermediate",
    "readingTimeMin": 6,
    "blurb": "Top-k twice: a cheap comparator to shortlist, an expensive one to decide."
  },
  {
    "slug": "segment-tree",
    "title": "Segment Tree",
    "category": "Data Structures",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "Range queries and point updates in logarithmic time."
  },
  {
    "slug": "semantic-cache",
    "title": "Semantic Cache",
    "category": "AI Systems",
    "difficulty": "Intermediate",
    "readingTimeMin": 6,
    "blurb": "A cache whose key is a vector — so a hit is a judgement call, and it can be wrong."
  },
  {
    "slug": "sharding-replication",
    "title": "Sharding & Replication",
    "category": "Distributed Systems",
    "difficulty": "Advanced",
    "readingTimeMin": 6,
    "blurb": "Route keys to shards and compare quorum vs asynchronous replication."
  },
  {
    "slug": "skip-list",
    "title": "Skip List",
    "category": "Data Structures",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Probabilistic search structure."
  },
  {
    "slug": "snowflake-id",
    "title": "Snowflake IDs",
    "category": "Distributed Systems",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "K-ordered unique IDs at scale."
  },
  {
    "slug": "sorting-race",
    "title": "Sorting Race",
    "category": "Algorithms",
    "difficulty": "Beginner",
    "readingTimeMin": 3,
    "blurb": "Bubble vs Quick vs Merge — same array, side by side."
  },
  {
    "slug": "sparse-matrix",
    "title": "Sparse Matrix",
    "category": "Data Structures",
    "difficulty": "Intermediate",
    "readingTimeMin": 5,
    "blurb": "Store only non-zero cells instead of the full grid."
  },
  {
    "slug": "speculative-decoding",
    "title": "Speculative Decoding",
    "category": "AI Systems",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "Guess ahead cheaply, verify in bulk, keep the prefix that survives."
  },
  {
    "slug": "stack",
    "title": "Stack",
    "category": "Data Structures",
    "difficulty": "Beginner",
    "readingTimeMin": 3,
    "blurb": "Last-in, first-out storage for nested work."
  },
  {
    "slug": "strongly-connected-components",
    "title": "Strongly Connected Components",
    "category": "Algorithms",
    "difficulty": "Advanced",
    "readingTimeMin": 6,
    "blurb": "Find maximal mutually reachable groups in directed graphs."
  },
  {
    "slug": "timsort",
    "title": "TimSort",
    "category": "Algorithms",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "Production hybrid sort optimized for real-world partially ordered data."
  },
  {
    "slug": "tls-handshake",
    "title": "TLS Handshake",
    "category": "Security",
    "difficulty": "Advanced",
    "readingTimeMin": 6,
    "blurb": "The foundation of HTTPS."
  },
  {
    "slug": "tokenization",
    "title": "Tokenization & BPE",
    "category": "AI Systems",
    "difficulty": "Intermediate",
    "readingTimeMin": 6,
    "blurb": "A trie walk over merges a corpus voted for — and the unit you are billed in."
  },
  {
    "slug": "topological-sort",
    "title": "Topological Sort",
    "category": "Algorithms",
    "difficulty": "Intermediate",
    "readingTimeMin": 4,
    "blurb": "Order dependent work in a DAG with Kahn's algorithm."
  },
  {
    "slug": "tree-dp",
    "title": "Tree DP",
    "category": "Algorithms",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "Return multiple states per node and combine child answers."
  },
  {
    "slug": "trie",
    "title": "Trie (Prefix Tree)",
    "category": "Data Structures",
    "difficulty": "Beginner",
    "readingTimeMin": 3,
    "blurb": "The engine of autocomplete."
  },
  {
    "slug": "vector-clocks",
    "title": "Vector Clocks",
    "category": "Distributed Systems",
    "difficulty": "Advanced",
    "readingTimeMin": 6,
    "blurb": "Detecting causality and conflicts."
  },
  {
    "slug": "vector-index",
    "title": "Vector Index: Recall vs Latency",
    "category": "AI Systems",
    "difficulty": "Advanced",
    "readingTimeMin": 6,
    "blurb": "The index tradeoff you already know, except now the index can be wrong."
  },
  {
    "slug": "webauthn",
    "title": "WebAuthn / Passkeys",
    "category": "Security",
    "difficulty": "Advanced",
    "readingTimeMin": 5,
    "blurb": "The end of the password."
  }
];

/** Every declared bridge, flattened. Source of truth for both directions. */
export interface BridgeEdge {
  /** The lab that declares the bridge — the newer idea. */
  to: string;
  /** The prerequisite it is a small delta from. */
  from: string;
  sameness: string;
  delta: string;
}

export const bridgeEdges: BridgeEdge[] = [
  {
    "to": "agent-loop",
    "from": "topological-sort",
    "sameness": "Tool calls form a dependency graph and run in dependency order: a step whose inputs are not ready cannot execute, and a step whose inputs failed never becomes ready. That is the ordering you already implemented.",
    "delta": "The graph does not exist yet. The model emits one call at a time and decides the next after seeing the result, so there is no whole graph to sort and no way to detect a cycle in advance — a loop only shows up as the same call repeating. Kahn's algorithm terminates because the graph is finite; this terminates because you gave it a step budget."
  },
  {
    "to": "agent-loop",
    "from": "circuit-breaker",
    "sameness": "Same containment around an unreliable dependency: watch failures, stop calling something that keeps failing, and fail the operation rather than hanging on it forever.",
    "delta": "The dependency is non-deterministic, so 'failing' now includes succeeding with a plausible wrong answer. No error rate detects that, which is why the budget is the primary guard rather than the error threshold — the loop is bounded by steps and tokens spent, not only by exceptions raised."
  },
  {
    "to": "ann-search",
    "from": "skip-list",
    "sameness": "HNSW IS a skip list. A sparse top layer takes huge strides across the whole set, each layer below is denser, and you descend a layer the moment the current one stops improving — the same express-lane-then-local-lane trick you already implemented, with the same probabilistic layer assignment per node.",
    "delta": "A skip list keys on a total order, so 'too far, drop a level' is always correct. Distance in 300 dimensions gives no total order, so the greedy walk is a heuristic: it can settle on a point that beats all its neighbours while a nearer one sits elsewhere in the graph. A skip list never returns the wrong node. This does, and cannot tell you when it has."
  },
  {
    "to": "ann-search",
    "from": "quadtree",
    "sameness": "Same premise as the quadtree: partition space so a lookup touches a small region rather than every point, and let the structure of the data decide where the cuts go.",
    "delta": "Recursive partitioning collapses past roughly ten dimensions — the cells needed to cover the space outgrow the points, and every query ends up touching most of them anyway. So high-dimensional search abandons partitioning for a navigable graph: nodes hold links to a few near neighbours plus a couple of deliberately long-range ones, and you walk edges instead of descending cells."
  },
  {
    "to": "attention",
    "from": "hash-table",
    "sameness": "The vocabulary is not a metaphor. Attention has queries, keys and values, and it does the same thing your hash table did: present a query, find the keys it matches, return the associated values.",
    "delta": "The match is soft. Instead of one bucket, every key gets a weight from the softmax and the result is the weighted sum of all values — so there is no miss, no collision, and no 'not found'. That is also the cost: a lookup is O(n) in the number of keys, not O(1), and with n keys per query the whole layer is O(n²)."
  },
  {
    "to": "attention",
    "from": "sparse-matrix",
    "sameness": "The attention matrix is n×n and, in a decoder, structurally half empty — no position may attend to a future one, so everything above the diagonal is masked out. You already know how to represent and skip that triangle.",
    "delta": "Those zeros are a rule rather than absent data, so they cannot be dropped from the layout: the mask is applied before the softmax, as -∞, because a zero score is still a real weight after exponentiating. And the dense half is what hurts — it grows quadratically with context length, which is why FlashAttention tiles the computation instead of ever materialising the matrix."
  },
  {
    "to": "continuous-batching",
    "from": "message-queue",
    "sameness": "It IS a work queue with a fixed pool of workers. Requests arrive, wait for a slot, occupy it for a while, and free it. The batch slots are the consumers and the scheduler decides who gets one next.",
    "delta": "A slot is not held for one message but for hundreds of sequential decode steps, and every occupied slot advances by one token in lockstep each step. So the unit of work is a step across the whole batch, not a message."
  },
  {
    "to": "continuous-batching",
    "from": "backpressure",
    "sameness": "The admission decision is the same one you implemented: a bounded pool, an arrival rate that may exceed it, and a policy for what happens to the excess.",
    "delta": "Rejecting is rarely acceptable here, so the excess queues and the pressure surfaces as time-to-first-token instead of dropped work. KV cache memory, not slot count, is usually the real bound."
  },
  {
    "to": "embeddings",
    "from": "sparse-matrix",
    "sameness": "A bag-of-words document IS a row of a sparse matrix — one column per vocabulary term, almost every entry zero. You already stored it that way, and you already compared two documents by walking their non-zero entries.",
    "delta": "An embedding is that row compressed to a few hundred dense dimensions, and the compression is learned rather than structural. The consequence is the whole point: sparse rows overlap only when they share literal tokens, so 'car' and 'automobile' score zero. Dense rows can be close without sharing a single term."
  },
  {
    "to": "embeddings",
    "from": "hash-table",
    "sameness": "It is still key-to-value lookup, and the key is still derived from the content itself rather than assigned.",
    "delta": "A hash deliberately destroys similarity — one changed character must scatter the key across the table, which is what keeps buckets even. An embedding deliberately preserves it. So there is no exact-match probe and no collision to resolve; 'lookup' becomes 'find the nearest points', and every query returns something, whether or not anything relevant exists."
  },
  {
    "to": "inference-cost",
    "from": "rate-limiter",
    "sameness": "It is the token bucket you implemented, with the units changed. A budget refills over time, each request draws from it, and exceeding the rate means queueing or rejection.",
    "delta": "The tokens are literally the model's tokens, priced differently for input and output, so the bucket is denominated in money as well as in requests per second."
  },
  {
    "to": "inference-cost",
    "from": "load-balancer",
    "sameness": "Capacity planning is the same arithmetic: concurrency divided by service time gives throughput, and offered load above that queues.",
    "delta": "Service time is not roughly constant. It scales with the number of output tokens, so two requests to the same endpoint can differ by a factor of fifty and capacity is a moving target."
  },
  {
    "to": "kv-cache",
    "from": "lru-cache",
    "sameness": "It IS an LRU cache. Keys are sequences, values are their attention tensors, and the eviction policy is the same recency ordering you implemented — the least recently touched conversation is the one that goes.",
    "delta": "The budget is GPU memory rather than entry count, so entries have wildly different sizes. And an eviction is not a miss you refetch — it is a recompute of every token in that sequence, which is why it shows up as a latency spike rather than an error."
  },
  {
    "to": "prompt-injection",
    "from": "jwt-anatomy",
    "sameness": "Same shape as the unverified token you took apart: data arrives from outside carrying a claim about what it is allowed to do, and everything depends on whether the receiver checks that claim or takes its word.",
    "delta": "There is nothing to check. A JWT has a signature, so 'is this claim authentic' is a computation with an answer. Instructions and content share one undifferentiated text channel with no envelope, no signature, and no delimiter the model is obliged to respect — so the boundary cannot be verified at parse time. It has to be enforced by what the tools permit after the model has already been convinced."
  },
  {
    "to": "prompt-injection",
    "from": "cors-lab",
    "sameness": "Same question CORS exists to answer: this content came from somewhere else, so what is it allowed to reach? Origin, and the privileges attached to it, is the whole subject.",
    "delta": "CORS is enforced by the browser, outside the page's control. Nothing enforces this. Once a retrieved document is in the context window it is the same colour as the system prompt as far as the model is concerned, so origin has to be tracked by your own code and carried forward — a call built on data from an untrusted document is itself untrusted, however trustworthy the caller looked."
  },
  {
    "to": "quantization",
    "from": "bitset",
    "sameness": "It is the same packing you implemented: values that do not need a full machine word share one, and reading a value means an offset plus a mask. Memory falls geometrically with the bits per value.",
    "delta": "The packed values are approximations rather than exact booleans, so packing now costs accuracy. You also need a scale factor per group to map the small integer range back onto real weights."
  },
  {
    "to": "quantization",
    "from": "huffman-coding",
    "sameness": "Both spend bits in proportion to how much they matter. Huffman gives frequent symbols shorter codes; quantisation gives each weight group only as many levels as its range justifies.",
    "delta": "Quantisation is lossy and fixed-width, so it is chosen for predictable memory and fast decode rather than for optimal compression."
  },
  {
    "to": "rag-pipeline",
    "from": "embeddings",
    "sameness": "Stage zero is the lab you just did. Chunks are embedded once at ingest, the question is embedded at query time, and relevance is the cosine between them.",
    "delta": "The two sides are no longer symmetric. A question and the passage answering it rarely look alike — 'why did the deploy fail' and a log excerpt share almost no vocabulary — so query and document are often embedded by different modes of the same model, and pure similarity retrieves things about the topic rather than things that answer it."
  },
  {
    "to": "rag-pipeline",
    "from": "ann-search",
    "sameness": "Stage one is the approximate search you built, with the same recall you already learned to measure against a brute-force baseline.",
    "delta": "Its misses now arrive somewhere new. A neighbour the graph never visited is not a slightly worse search result any more — it is a passage the model never sees, so the answer comes out fluent, confident and unsupported. Retrieval failures surface as hallucinations, which is why they get blamed on the model."
  },
  {
    "to": "rag-pipeline",
    "from": "reranking",
    "sameness": "Stage two is the two-stage ranker, unchanged: a cheap shortlist, an expensive cross-encoder, the same ceiling set by first-stage recall.",
    "delta": "There is now a third cut after it that has nothing to do with relevance. The context window is finite, so the best passages are packed until the budget runs out and the rest are dropped — a document can be ranked first by every scorer in the pipeline and still not make it into the prompt."
  },
  {
    "to": "reranking",
    "from": "heap-priority-queue",
    "sameness": "This is top-k, the operation you already implemented with a heap: keep the k best seen so far, evict the worst as better ones arrive, never sort the whole input.",
    "delta": "The comparator changes between stages. Stage one ranks thousands of candidates by a cheap similarity you already have; stage two re-scores a shortlist with a cross-encoder that reads the query and the document together. Comparisons are no longer free — each one is a model call worth roughly ten milliseconds — so the shortlist size, not the heap, is what the design is about."
  },
  {
    "to": "reranking",
    "from": "quickselect",
    "sameness": "Same insight as quickselect: you never needed the whole ordering, only the boundary between the top group and the rest, so most of the sorting work was waste.",
    "delta": "Quickselect wins by doing less work on a fixed input. Here the two stages score different things — the cheap score is a proxy, the expensive one is closer to what you actually want — so cutting the shortlist does not merely save time, it discards documents the accurate scorer would have ranked first. A perfect stage-two model cannot recover a document stage one dropped."
  },
  {
    "to": "semantic-cache",
    "from": "lru-cache",
    "sameness": "Same cache you already built. Keyed store in front of an expensive call, hit and miss counters, and least-recently-used eviction when it fills — nothing about that changes.",
    "delta": "The key is an embedding and the comparison is a similarity threshold, so a hit is a decision rather than a fact. An LRU cache that misses costs you latency; a semantic cache that hits too loosely returns another question's answer, confidently, with no error anywhere. The failure mode moves from performance to correctness."
  },
  {
    "to": "semantic-cache",
    "from": "consistent-hashing",
    "sameness": "Same machinery as the hash ring: hash the content, and let where it lands decide what happens to it. Both systems live or die on how the hash distributes.",
    "delta": "The goal is inverted. Consistent hashing wants similar keys spread evenly across the ring — that uniformity is the whole point, and two nearly identical keys landing on the same node would be a flaw. Locality-sensitive hashing wants the opposite: near-identical inputs must collide on purpose, because a collision is the cache hit. Same tool, requirements reversed."
  },
  {
    "to": "speculative-decoding",
    "from": "branch-and-bound",
    "sameness": "It is the same speculate-then-prune shape you implemented: explore a candidate path cheaply, evaluate it against something authoritative, and discard everything after the point it stops holding up.",
    "delta": "The cheap explorer is a small language model rather than a bound function, and verification is exact rather than a heuristic — a rejected token costs wasted GPU time but never a wrong answer."
  },
  {
    "to": "tokenization",
    "from": "trie",
    "sameness": "Encoding is a longest-match walk over a prefix structure — the same operation you implemented for autocomplete. Feed characters, follow the longest sequence the vocabulary knows, emit it, continue from there.",
    "delta": "The entries were not defined by anyone; they were learned by counting pairs in a training corpus. So the vocabulary reflects that corpus's habits: ' the' is one token, an uncommon surname is five, and the same sentence in Hindi or Thai can cost three times what it costs in English. Your trie was a data structure. This one is a pricing model."
  },
  {
    "to": "tokenization",
    "from": "huffman-coding",
    "sameness": "Identical greedy loop: count frequencies, repeatedly combine the pair that pays best, and end with common things encoded short and rare things encoded long. Both are frequency-driven compression built bottom-up.",
    "delta": "Huffman merges the two least frequent symbols and runs to optimality. BPE merges the most frequent adjacent pair and stops at a fixed vocabulary size — usually 32k to 200k — because the output is not a bitstream but a symbol table an embedding matrix must have a row for. That cap is why rare words fragment: there was no budget left for them."
  },
  {
    "to": "vector-index",
    "from": "btree-index",
    "sameness": "Same bargain as the B-tree index you built: pay memory and write amplification up front so a read touches a few pages instead of the whole table. Clusters are the pages, the centroid list is the root, and choosing how much of the index to open is still the query planner's job.",
    "delta": "A B-tree read is exact — if the row is there, the index finds it, every time. A vector index answers 'probably'. Opening fewer clusters does not just cost you speed, it silently changes the answer, so the tuning knob is not latency versus throughput but latency versus correctness, measured as recall against a brute-force baseline."
  },
  {
    "to": "vector-index",
    "from": "bloom-filter",
    "sameness": "You have already shipped a structure that trades exactness for size, with an error rate you dial deliberately. Same deal here: a fixed budget buys a fixed quality of answer, and you choose the point on the curve.",
    "delta": "A Bloom filter's error is one-sided — a false positive, which a lookup in the real store immediately corrects. A vector index errs the other way: it returns false negatives, neighbours it never looked at. There is no cheap verification step, because verifying means the exact scan the index exists to avoid. So the error is invisible in production and must be measured offline."
  }
];
