#!/usr/bin/env node
// Reads src/content/labs/*.ts and emits:
//   - src/content/labs.gen.ts  (small summary index for pages that only list labs)
//   - public/sitemap.xml
// Also validates content integrity and exits non-zero on failure, so a bad slug
// or a dangling bridge fails the build instead of shipping.
//
// Lab files are pure data with a single type-only import, so they can be
// evaluated directly after stripping the TS bits — no parser needed.
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const labsDir = join(repoRoot, "src", "content", "labs");
const SITE = process.env.SITE_URL || "https://jainilchauhan.com";

const SUMMARY_FIELDS = ["slug", "title", "category", "difficulty", "readingTimeMin", "blurb"];

function loadLab(file) {
  const src = readFileSync(join(labsDir, file), "utf8");
  const body = src
    .replace(/^import type .*$/gm, "")
    .replace(/export const lab: LabMeta =/, "return");
  try {
    return new Function(body)();
  } catch (err) {
    throw new Error(`${file}: failed to evaluate — ${err.message}`);
  }
}

function main() {
  const files = readdirSync(labsDir)
    .filter((f) => f.endsWith(".ts") && f !== "index.ts")
    .sort();

  const labs = [];
  const errors = [];

  for (const file of files) {
    const lab = loadLab(file);
    const expected = file.slice(0, -3);
    if (lab.slug !== expected) {
      errors.push(`${file}: slug "${lab.slug}" does not match filename`);
    }
    for (const field of ["title", "category", "difficulty", "blurb", "concept"]) {
      if (!lab[field]) errors.push(`${lab.slug}: missing ${field}`);
    }
    labs.push(lab);
  }

  const slugs = new Set(labs.map((l) => l.slug));
  if (slugs.size !== labs.length) errors.push("duplicate slugs present");

  // Every bridge must point at a lab that exists, or the bridge map renders a
  // dead "you already know X" claim about nothing.
  for (const lab of labs) {
    for (const b of lab.bridgesFrom ?? []) {
      if (!slugs.has(b.slug)) {
        errors.push(`${lab.slug}: bridgesFrom "${b.slug}" does not exist`);
      }
      if (b.slug === lab.slug) errors.push(`${lab.slug}: bridges to itself`);
    }
    for (const t of lab.challenge?.tests ?? []) {
      if (!t.name || !t.body) errors.push(`${lab.slug}: challenge test missing name/body`);
    }
    if (lab.challenge && lab.challenge.tests.length === 0) {
      errors.push(`${lab.slug}: challenge has no tests`);
    }
  }

  if (errors.length) {
    console.error("[content] validation failed:");
    for (const e of errors) console.error("  - " + e);
    process.exit(1);
  }

  const summaries = labs.map((lab) => Object.fromEntries(SUMMARY_FIELDS.map((f) => [f, lab[f]])));

  const gen =
    `// Generated by scripts/generate-content.mjs. Do not edit.\n` +
    `// Summary fields only — full lab content is lazily imported per slug from\n` +
    `// src/content/labs/<slug>.ts. Regenerate with \`npm run build\`.\n` +
    `import type { LabCategory, Difficulty } from "./types";\n\n` +
    `export interface LabSummary {\n` +
    `  slug: string;\n  title: string;\n  category: LabCategory;\n` +
    `  difficulty: Difficulty;\n  readingTimeMin: number;\n  blurb: string;\n}\n\n` +
    `export const labSummaries: LabSummary[] = ${JSON.stringify(summaries, null, 2)};\n`;

  writeFileSync(join(repoRoot, "src", "content", "labs.gen.ts"), gen, "utf8");

  const today = new Date().toISOString().slice(0, 10);
  const urls = [
    { loc: `${SITE}/`, priority: "1.0", freq: "monthly" },
    { loc: `${SITE}/lab`, priority: "0.8", freq: "weekly" },
    ...labs.map((l) => ({
      loc: `${SITE}/lab/${l.slug}`,
      priority: "0.6",
      freq: "monthly",
    })),
  ];

  const xml =
    `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
    urls
      .map(
        (u) =>
          `  <url>\n    <loc>${u.loc}</loc>\n    <lastmod>${today}</lastmod>\n` +
          `    <changefreq>${u.freq}</changefreq>\n    <priority>${u.priority}</priority>\n  </url>`,
      )
      .join("\n") +
    `\n</urlset>\n`;

  writeFileSync(join(repoRoot, "public", "sitemap.xml"), xml, "utf8");

  const withChallenge = labs.filter((l) => l.challenge).length;
  const withBridge = labs.filter((l) => l.bridgesFrom?.length).length;
  console.log(
    `[content] ${labs.length} labs — ${withChallenge} with challenges, ` +
      `${withBridge} with bridges. Wrote labs.gen.ts + sitemap.xml (${urls.length} urls).`,
  );
}

main();
