import type { LabMeta } from "../types";

export const lab: LabMeta = {
  slug: "activity-selection",
  title: "Activity Selection",
  category: "Algorithms",
  difficulty: "Beginner",
  readingTimeMin: 3,
  blurb: "Greedily choose compatible activities with equal value.",
  caption:
    "Activities with equal value reduce to interval scheduling. Pick the next activity that finishes earliest.",
  skillTags: ["DSA", "Greedy"],
  concept:
    "Activity selection is the classic greedy scheduling problem: given start and finish times, choose the maximum number of mutually compatible activities. When every activity has equal value, earliest-finish-time greedy is optimal.\n\nThe problem teaches the exchange argument: replace the first activity in an optimal solution with the earliest finishing compatible one without making the solution worse.",
  complexity: [
    { operation: "After sorting", time: "O(n)", space: "O(1)" },
    { operation: "Including sort", time: "O(n log n)", space: "O(1) to O(n)" },
  ],
  realWorld: [
    "Single-machine scheduling, classroom planning, task windows, and interview scheduling.",
  ],
  pitfalls: [
    "Not suitable when activities have different profit.",
    "Requires known start/end times.",
    "Overlapping definition affects compatibility.",
  ],
  codeSnippet: {
    language: "py",
    code: `# Greedy "earliest finishing first" with an exchange-argument proof:
# any optimal solution can swap its first activity for ours without getting worse.
def select(activities):
    chosen, last_end = [], float("-inf")
    for a in sorted(activities, key=lambda a: a["end"]):
        if a["start"] >= last_end:
            chosen.append(a)
            last_end = a["end"]
    return chosen

# Weighted variant breaks the greedy proof -> needs DP with binary search.`,
  },
  usedBy: [
    {
      company: "Microsoft",
      product: "Outlook scheduling assistant",
      usage:
        "Suggested meeting slots are generated by scanning free/busy intervals and packing compatible ones.",
      href: "https://learn.microsoft.com/en-us/graph/api/user-findmeetingtimes",
    },
    {
      company: "Delta / airline operations",
      product: "Gate and runway slot assignment",
      usage:
        "Aircraft turns are assigned to gates by earliest-free ordering under fixed occupancy windows.",
    },
    {
      company: "Databricks",
      product: "Cluster job window packing",
      usage:
        "Scheduled jobs with known runtimes are packed into cluster uptime windows to reduce idle spin-up cost.",
    },
  ],
  references: [
    {
      label: "Microsoft Graph — findMeetingTimes",
      href: "https://learn.microsoft.com/en-us/graph/api/user-findmeetingtimes",
    },
    {
      label: "Greedy algorithms — exchange argument notes",
      href: "https://www.cs.princeton.edu/~wayne/kleinberg-tardos/pdf/04GreedyAlgorithmsI.pdf",
    },
  ],
};
