import type { LabMeta } from "../types";

export const lab: LabMeta = {
  slug: "activity-selection",
  title: "Activity Selection",
  category: "Algorithms",
  difficulty: "Beginner",
  readingTimeMin: 3,
  blurb: "Greedily choose compatible activities with equal value.",
  caption:
    "Activities with equal value reduce to interval scheduling. Pick the next activity that finishes earliest.",
  skillTags: ["DSA", "Greedy"],
  bridgesFrom: [
    {
      slug: "sorting-race",
      sameness:
        "The algorithm IS a sort. Order the activities by finish time and what remains is a single linear pass that takes anything starting after the last one you kept — the sort is doing all of the work.",
      delta:
        "Because the sort dominates, the whole thing is O(n log n) and the scan is free, which means correctness lives entirely in the comparator. Sort by start time, or by duration, or by earliest start instead, and the identical one-pass scan returns a confidently wrong answer with no error and no warning. Greedy algorithms are not fragile in their loop; they are fragile in their sort key.",
    },
  ],
  concept:
    "Activity selection is the classic greedy scheduling problem: given start and finish times, choose the maximum number of mutually compatible activities. When every activity has equal value, earliest-finish-time greedy is optimal.\n\nThe problem teaches the exchange argument: replace the first activity in an optimal solution with the earliest finishing compatible one without making the solution worse.",
  complexity: [
    { operation: "After sorting", time: "O(n)", space: "O(1)" },
    { operation: "Including sort", time: "O(n log n)", space: "O(1) to O(n)" },
  ],
  realWorld: [
    "Single-machine scheduling, classroom planning, task windows, and interview scheduling.",
  ],
  pitfalls: [
    "Not suitable when activities have different profit.",
    "Requires known start/end times.",
    "Overlapping definition affects compatibility.",
  ],
  codeSnippet: {
    language: "py",
    code: `# Greedy "earliest finishing first" with an exchange-argument proof:
# any optimal solution can swap its first activity for ours without getting worse.
def select(activities):
    chosen, last_end = [], float("-inf")
    for a in sorted(activities, key=lambda a: a["end"]):
        if a["start"] >= last_end:
            chosen.append(a)
            last_end = a["end"]
    return chosen

# Weighted variant breaks the greedy proof -> needs DP with binary search.`,
  },
  usedBy: [
    {
      company: "Microsoft",
      product: "Outlook scheduling assistant",
      usage:
        "Suggested meeting slots are generated by scanning free/busy intervals and packing compatible ones.",
      href: "https://learn.microsoft.com/en-us/graph/api/user-findmeetingtimes",
    },
    {
      company: "Delta / airline operations",
      product: "Gate and runway slot assignment",
      usage:
        "Aircraft turns are assigned to gates by earliest-free ordering under fixed occupancy windows.",
    },
    {
      company: "Databricks",
      product: "Cluster job window packing",
      usage:
        "Scheduled jobs with known runtimes are packed into cluster uptime windows to reduce idle spin-up cost.",
    },
  ],
  references: [
    {
      label: "Microsoft Graph — findMeetingTimes",
      href: "https://learn.microsoft.com/en-us/graph/api/user-findmeetingtimes",
    },
    {
      label: "Greedy algorithms — exchange argument notes",
      href: "https://www.cs.princeton.edu/~wayne/kleinberg-tardos/pdf/04GreedyAlgorithmsI.pdf",
    },
  ],
  challenge: {
    prompt:
      "Choose as many non-overlapping activities as possible. Sorting by earliest finish time is optimal, and the reason is worth internalising: finishing earliest leaves the most room for everything after it.",
    entry: "selectActivities",
    starter: `/**
 * @param {Array<[number, number]>} activities - [start, end], end exclusive so
 *   an activity ending at 5 does not clash with one starting at 5.
 * @returns {number} the most activities that can be chosen without overlap.
 */
function selectActivities(activities) {
  // Sort by END time, not by start and not by duration. Then take greedily.
}
`,
    tests: [
      {
        name: "picks the compatible pair",
        body: `assertEquals(solution([[1, 3], [2, 5], [3, 6]]), 2);`,
      },
      {
        name: "touching activities do not clash",
        body: `assertEquals(solution([[1, 2], [2, 3]]), 2);`,
      },
      {
        name: "sorting by start would be wrong here",
        body: `assertEquals(solution([[1, 10], [2, 3], [4, 5]]), 2);`,
      },
      {
        name: "all overlapping",
        body: `assertEquals(solution([[1, 5], [2, 6], [3, 7]]), 1);`,
      },
      {
        name: "no activities",
        body: `assertEquals(solution([]), 0);`,
      },
      {
        name: "a single activity",
        body: `assertEquals(solution([[0, 1]]), 1);`,
      },
      {
        name: "input order does not matter",
        body: `assertEquals(solution([[3, 6], [1, 3], [2, 5]]), 2);`,
      },
      {
        name: "handles many activities",
        body: `var acts = [];
for (var i = 0; i < 50000; i++) acts.push([i, i + 1]);
assertEquals(solution(acts), 50000);`,
      },
    ],
    hints: [
      "Sort a copy by end time ascending.",
      "Track when the last chosen activity finished, starting at negative infinity.",
      "Take an activity when its start is greater than or equal to that finish time.",
    ],
    reference: `function selectActivities(activities) {
  // Earliest finish first: this is the exchange argument -- any optimal set can
  // swap its first activity for the earliest-finishing one and stay valid.
  const sorted = activities.slice().sort((a, b) => a[1] - b[1]);
  let count = 0;
  let freeAt = -Infinity;
  for (const [start, end] of sorted) {
    if (start >= freeAt) {
      count++;
      freeAt = end;
    }
  }
  return count;
}
`,
  },
};
